version: "3"
networks:
  coco-annotator_cocoannotator:
    external: true

services:
  mongo-express:
    image: mongo-express
    container_name: annotator_mongodbexp
    restart: always
    ports:
      - 8081:8081
    networks:
      - coco-annotator_cocoannotator
